### ISSUE TITLE
Add Contributors.md in Readme

### ISSUE THREAD

**Issue by SanjeevKumar22** [QAZIMAAZARSHAD/Income-Tax-Calcultor#58]
contributor in readme

**Comment by jigar-sable** [comment]
@QAZIMAAZARSHAD Once have look at this I'd made those changes. 

- As there was one point in PR template that added yourself as a contributor in readme so that I've made it in tabular format and comment is also there if someone wants to add.

![image](https://user-images.githubusercontent.com/64949957/121774499-4bb08e80-cba0-11eb-920f-3c2133c4364b.png)

**Comment by sb25710** [comment]
Hey is this issue still open, and do you often need documentation help?
I am actively looking for open source work

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD Once have look at this I'd made those changes.
> 
> * As there was one point in PR template that added yourself as a contributor in readme so that I've made it in tabular format and comment is also there if someone wants to add.
> 
> ![image](https://user-images.githubusercontent.com/64949957/121774499-4bb08e80-cba0-11eb-920f-3c2133c4364b.png)

This issue is closed @jigar-sable.

**Comment by QAZIMAAZARSHAD** [comment]
> > @QAZIMAAZARSHAD Once have look at this I'd made those changes.
> > 
> > * As there was one point in PR template that added yourself as a contributor in readme so that I've made it in tabular format and comment is also there if someone wants to add.
> > 
> > ![image](https://user-images.githubusercontent.com/64949957/121774499-4bb08e80-cba0-11eb-920f-3c2133c4364b.png)
> 
> This issue is closed @jigar-sable.

But this design is better, you can open a new issue to update.

**Comment by jigar-sable** [comment]
Okay
